chart_dir: "/home/storage/CAIG_project/Ice_chart/"
supp_dir: "/home/storage/CAIG_project/Supplement/" 
chart_date0: "20250512"
times_dir: "/home/storage/CAIG_project/TS/" 
times_date0: "2019-01-01"
times_date1: "2020-01-01"
crs: 'EPSG:3413'
pixel_size: 160
starti: 0
target_chart: "NIC"
radius_pixel: 512
overwrite: False
existing: False
POLARIZATION: 'HH'
INSTRUMENT_MODE: 'EW'
PLATFORM: 'A'
