name: weakly-supervised-sea-ice-book
channels:
 - conda-forge
 - default
dependencies:
 - python ~=3.12

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 # Jupyterlab for notebooks
 - jupyterlab

 # Data Access
 - earthaccess

 # Plotting
 - matplotlib
 - cartopy

 # xarray
 - xarray
 - netCDF4
 - h5py
 - h5netcdf
 - dask
 - bottleneck
 - rioxarray

 # pandas and geopandas
 - pandas
 - geopandas
 - openpyxl

 # Quarto
 - quarto
 
